# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    # Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} -X main.projectName={{.ProjectName}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: '386'
      - goos: windows
        goarch: arm
    # Path to main.go file or main package.
    # Default is `.`.
    main: ./cmd/main.go
archives:
  - formats: [ tar.gz ]
    format_overrides:
      - goos: windows
        formats: [ zip ]
    files:
      - LICENSE
      - README.md
sboms:
  - id: archive
    artifacts: archive
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: desc
  filters:
    exclude:
      - '^doc[s]?:'
      - '^\[doc[s]?\]'
      - '^wip:'
      - '^WIP:'
docker_digest:
  name_template: "digests.txt"
dockers_v2:
  - images:
      - "jimschubert/changelog"
    tags:
      - "latest"
      - "{{ .Tag }}"
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
    dockerfile: release.Dockerfile
    labels:
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.name": "{{ .ProjectName }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "https://github.com/jimschubert/changelog"
      "org.opencontainers.image.licenses": "Apache-2.0"
    build_args:
      APP_NAME: "{{ .ProjectName }}"
