name: Go Build
on:
  push:
    branches:
      - 'master'
      - 'releases/v*'
    tags:
      - 'v*'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache go module
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
        id: go

      - name: Build and Test
        run: go test -v -race -cover ./...

  release:
    runs-on: ubuntu-latest
    needs: build
    name: Build, Tag, Push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          args: release --clean
